### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character

### ISSUE THREAD

**Issue by pybokeh** [dddomodossola/remi#75] opened 2015-11-16 00:06 UTC
**Full traceback:**
Traceback (most recent call last):
  File "/home/pybokeh/miniconda3/envs/remi/lib/python3.4/socketserver.py", line 617, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/pybokeh/miniconda3/envs/remi/lib/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "test.py", line 10, in __init__
    super(MyApp, self).__init__(*args)
  File "/home/pybokeh/miniconda3/envs/remi/lib/python3.4/socketserver.py", line 673, in __init__
    self.handle()
  File "/home/pybokeh/miniconda3/envs/remi/lib/python3.4/http/server.py", line 398, in handle
    self.handle_one_request()
  File "/home/pybokeh/miniconda3/envs/remi/lib/python3.4/http/server.py", line 386, in handle_one_request
    method()
  File "/home/pybokeh/miniconda3/envs/remi/lib/python3.4/site-packages/remi/server.py", line 552, in do_GET
    self.process_all(path)
  File "/home/pybokeh/miniconda3/envs/remi/lib/python3.4/site-packages/remi/server.py", line 572, in process_all
    self.wfile.write(encodeIfPyGT3(html))
  File "/home/pybokeh/miniconda3/envs/remi/lib/python3.4/site-packages/remi/server.py", line 90, in encodeIfPyGT3
    data = data.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2020' in position 20239: ordinal not in range(256)

### My code:
```python
import remi.gui as gui
from remi import start, App
import pandas as pd
from db import DB

# import ipdb; ipdb.set_trace()

class MyApp(App):
    def __init__(self, *args):
        super(MyApp, self).__init__(*args)

    def main(self):
        wid = gui.Widget(1200, 800, gui.Widget.LAYOUT_HORIZONTAL, 10)
        
        db = DB(filename="/home/pybokeh/Dropbox/data_sets/nba", dbtype="sqlite")

        column_names = [column.name for column in db.tables.player_game_stats._columns]

        row_data = db.query("select * from player_game_stats where team_name like '%Cav%'").values

        self.table = gui.Table(600, 400)

        row = gui.TableRow()
        for column in column_names:
            item = gui.TableTitle()
            item.append(str(id(item)), str(column))
            row.append(str(id(item)), item)

        self.table.append(str(id(row)), row)


        for _row in row_data:
            row = gui.TableRow()
            for row_item in _row:
                item = gui.TableTitle()
                item.append(str(id(item)), str(row_item))
                row.append(str(id(item)), item)

                self.table.append(str(id(row)), row)

        wid.append('1', self.table)

        return wid

if __name__ == "__main__":
    start(MyApp)
```

If I limit my query to return just 5 rows, I do not get an error.   So it seems there is a character that it doesn't like somewhere in the other rows in my table.

Using virtual environment created with **conda with python version 3.4**.

### My platform:
```python
import platform
print(platform.platform())
```
**Linux-3.13.0-68-generic-x86_64-with-debian-jessie-sid**

### Installed python libraries:
```python
import pip
modules = pip.get_installed_distributions()
for m in modules:
    print(m)
```
**setuptools 18.4
prettytable 0.7.2
ptyprocess 0.5
ipython 4.0.0
ipython-genutils 0.1.0
PyMeta3 0.5.1
numpy 1.10.1
traitlets 4.0.0
wheel 0.26.0
python-dateutil 2.4.2
pandas 0.17.0
pexpect 4.0.1
simplegeneric 0.8.1
pybars3 0.9.1
decorator 4.0.4
ipdb 0.8.1
pytz 2015.7
six 1.10.0
pickleshare 0.5
remi 0.1
db.py 0.4.4
pip 7.1.2
path.py 8.1.2**

Regards,
Daniel

**Comment by pybokeh** [comment] 2015-11-16 01:06
To make it work for me, I changed line 90 in server.py from:
```python
data = data.encode('latin-1')
```

to
```python
data = data.encode('utf-8')
```

I'm not a developer and only have intermediate Python knowledge.  So not sure if this is the proper solution or if it works with Python 2.X also.

**Comment by dddomodossola** [comment] 2015-11-16 04:06
Hi pybokeh. First of all thank you for your exhaustive report. I'm unable to reproduce the error and furthermore, the code line you changed applies only to python version less than 3. Considering you are working with 3.4, the encoding you changed should not take effect.
Maybe the detection of python version on your enviroment is faulty?

May I ask you to do this test?
```python
import sys
sys.version_info < (3,)
```

**Comment by pybokeh** [comment] 2015-11-16 04:19
@dddomodossola 
```python
import sys
sys.version_info < (3,)
```

It outputs "False"

**Comment by pybokeh** [comment] 2015-11-16 04:29
@dddomodossola 
My sample NBA sqlite3 database can be downloaded from [here](https://github.com/pybokeh/jupyter_notebooks/blob/master/remi/nba)  There is a cross symbol † in the player name.  This cross symbol is apparently the character that is causing problems.

**Comment by dddomodossola** [comment] 2015-11-16 05:06
@pybokeh 
Yeah, I've seen. Your solution to the problem works fine, but I'm trying to solve this also for version less than 3.

**Comment by dddomodossola** [comment] 2015-11-16 05:20
@pybokeh 
Now should be fixed. Can you run your example with python2.7 ?
Thank you so much for your help.

**Comment by pybokeh** [comment] 2015-11-16 23:10
Error: UnicodeEncodeError: 'ascii' codec can't encode character u'\u2020' in position 14: ordinal not in range(128)

full traceback:
Traceback (most recent call last):
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "test.py", line 10, in __init__
    super(MyApp, self).__init__(*args)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/site-packages/remi/server.py", line 552, in do_GET
    self.process_all(path)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/site-packages/remi/server.py", line 562, in process_all
    self.client.root = self.main(*self.server.userdata)
  File "test.py", line 62, in main
    item.append(str(id(item)), str(row_item))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2020' in position 14: ordinal not in range(128)

I installed remi via pip:
pip install git+https://github.com/dddomodossola/remi.git

So I'm assuming your latest patch was implement.
Python version 2.7.10 virtual environment installed with conda.

**Comment by dddomodossola** [comment] 2015-11-17 04:35
The problem seems to be the str() conversion you are doing. Should be:
```python
item.append(str(id(item)), row_item)
```

**Comment by pybokeh** [comment] 2015-11-17 09:16
My database query can return data that are of type int.  So herein lies the problem.  Your item.append() calls the html conversion code which calls s.repr() method.  An int doesn't have repr().  That is why I am forced to convert the table item to str.

**Below is the traceback when I don't ensure the table item is of type str:**
Traceback (most recent call last):
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "test.py", line 10, in __init__
    super(MyApp, self).__init__(*args)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/site-packages/remi/server.py", line 552, in do_GET
    self.process_all(path)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/site-packages/remi/server.py", line 571, in process_all
    html = self.client.root.repr(self.client)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/site-packages/remi/gui.py", line 196, in repr
    return super(Widget,self).repr(client, include_children)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/site-packages/remi/gui.py", line 97, in repr
    innerHTML = innerHTML + s.repr(client)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/site-packages/remi/gui.py", line 196, in repr
    return super(Widget,self).repr(client, include_children)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/site-packages/remi/gui.py", line 97, in repr
    innerHTML = innerHTML + s.repr(client)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/site-packages/remi/gui.py", line 196, in repr
    return super(Widget,self).repr(client, include_children)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/site-packages/remi/gui.py", line 97, in repr
    innerHTML = innerHTML + s.repr(client)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/site-packages/remi/gui.py", line 196, in repr
    return super(Widget,self).repr(client, include_children)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/site-packages/remi/gui.py", line 97, in repr
    innerHTML = innerHTML + s.repr(client)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/site-packages/remi/gui.py", line 196, in repr
    return super(Widget,self).repr(client, include_children)
  File "/home/pybokeh/miniconda3/envs/remipy2/lib/python2.7/site-packages/remi/gui.py", line 97, in repr
    innerHTML = innerHTML + s.repr(client)
AttributeError: 'int' object has no attribute 'repr'

**Comment by dddomodossola** [comment] 2015-11-17 14:24
You can do something like this:
```python
item.append( str(id(item)), u"%s" % row_item )
```

**Comment by pybokeh** [comment] 2015-11-17 22:31
Thanks that worked.  I'll have to do some studying on encodings.  :-)

**Comment by dddomodossola** [comment] 2015-11-17 23:41
It's the same for me ;-) 
Thank you for the information you reported in this issue, you helped me a lot improving remi.

**Closed** 2015-11-24 10:33 UTC
