### ISSUE TITLE
Save in editor not working

### ISSUE THREAD

**Issue by banzsolt** [dddomodossola/remi#126] opened 2016-09-15 13:47 UTC
I am failing to save any project that I am working on in the editor. When I try to save/save as I get the following error:

`
remi.server.ws   ERROR    error parsing websocket
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/remi-0.1-py2.7.egg/remi/server.py", line 252, in on_message
    callback(**param_dict)
  File "/usr/local/lib/python2.7/dist-packages/remi-0.1-py2.7.egg/remi/gui.py", line 446, in onclick
    return self.eventManager.propagate(self.EVENT_ONCLICK, [])
  File "/usr/local/lib/python2.7/dist-packages/remi-0.1-py2.7.egg/remi/gui.py", line 131, in propagate
    return getattr(listener['instance'], listener['funcname'])(*params)
  File "remi-master/editor/editor.py", line 534, in menu_save_clicked
    self.project.save(self.projectPathFilename, self.projectConfiguration)
  File "remi-master/editor/editor.py", line 244, in save
    _left = self.children['root'].style['left']
KeyError: 'left'
`

**Comment by dddomodossola** [comment] 2016-09-15 13:49
Thank you for reporting, I will check it in some hours.

**Comment by dddomodossola** [comment] 2016-09-15 15:13
@banzsolt I found the bug. Can you confirm the issue is fixed now?

**Comment by banzsolt** [comment] 2016-09-15 15:55
@dddomodossola yes, the save works now!

**Comment by dddomodossola** [comment] 2016-09-15 15:56
@banzsolt thank you!

**Closed by dddomodossola** 2016-09-15 15:56 UTC
