### ISSUE TITLE
Problem with vertical layout

### ISSUE THREAD

**Issue by Eothred** [dddomodossola/remi#403] opened 2020-09-11 06:40 UTC
I am using Remi commit 38b5a99 with Python 3.8 on Linux. The following demo is not rendering properly on my system:

```
import remi.gui as gui
from remi import start, App


class MyApp(App):

    # noinspection PyAttributeOutsideInit
    def main(self):

        self.tab = gui.GridBox(width="100%", height="100%")

        self.tab.set_from_asciiart(
            """
            | lbl1 |
            | lbl2 |
            | lbl3 |
            | lbl4 |
            """,
            20,
            20,
        )
        lbl1 = gui.Label("Some Label 1")
        lbl2 = gui.Label("Some Label 2")
        lbl3 = gui.Label("Some Label 3")
        lbl4 = gui.Label("Some Label 4")
        config_dict = {
            "lbl1": lbl1,
            "lbl2": lbl2,
            "lbl3": lbl3,
            "lbl4": lbl4
        }
        self.tab.append(config_dict)

        return self.tab

if __name__ == "__main__":
    start(MyApp, title="Demo")
```

Here is how it rendered in Firefox for me. As you can see, the bottom bar is put too high up. In Chrome I see similar problem but the line is drawn a little bit further down.
![image](https://user-images.githubusercontent.com/187567/92876015-ec9fcc80-f409-11ea-84e6-21dc1e7ee1c0.png)

What I noticed during reduction to this example, was that when I set the border between the elements to 0 in the asciiart (the ones that are now 20, 20 to exaggerate the problem), the problem disappears. Hence my guess is that it does not correctly count the number of pixels used including the spacing between the elements. A similar issue occurred when having a long vertical checkbox list. This issue came recently I think, but not sure. I had the code not doing this some months ago.

**Comment by dddomodossola** [comment] 2020-09-11 09:43
Thank you for reporting @Eothred , I will check it soon!

**Comment by Eothred** [comment] 2020-09-11 09:48
Colleague confirmed running on OSX. I checked my prebuilt versions and can pinpoint somewhere between 9c63d11 (renders as expected) and 5767ef2 (issue appears)

**Comment by dddomodossola** [comment] 2020-09-11 10:12
Thank you for the information ;-) The problem was caused by 38fda78b691e2614e2e7c983423216ca99bc345b .

**Comment by dddomodossola** [comment] 2020-09-11 10:14
@Eothred Pushed the fix please test and eventually close issue

**Comment by Eothred** [comment] 2020-10-13 13:51
Hi @dddomodossola, sorry for my terribly late reply. I checked and you are right the error in the demo example I sent you now behaves correctly. My full blown app still struggles with vertical space though, so I will try to find another demo that is a bit more minimal than my full application.

**Comment by dddomodossola** [comment] 2020-10-14 09:22
Hello @Eothred. No problem at all for the late reply. 
I see a problem in this demo:
- the grid layout assigns space to elements defined as percentage;
- the grid height is auto;
It is like an equation with two variables, where it is not possible to give it a solution. How should be sized the container?

In this case you must set a fixed size for the container, otherwise you should use a different container like Container or VBox.

**Comment by Eothred** [comment] 2020-10-14 10:00
Hmm, ok that could certainly be that I use the wrong container, but without the 5 px vertical spacing between elements it all rescales fine I think?

**Comment by dddomodossola** [comment] 2020-10-14 10:18
@Eothred Yes that's right, but however the spacing is set to css as is, remi doesn't make special operations over it. I inspected css and calculated that rows height + spacing is within 100%. The problem is that the browser is not taking into account that spacing in height calculation, and we have no control over it.
Maybe you can set spacing as 0 and simale the spacing by children margins. (I tried this and works, but I specified a fixed size margin in pixels)

**Comment by Eothred** [comment] 2020-10-14 11:11
OK, I will avoid using the spacing in this way. I made a suggestion in ad222c4 to throw an error when the user tries to set this kind of combo, maybe something like that would block others from doing the same mistake? If you think it makes sense I can make a pull request.

**Comment by dddomodossola** [comment] 2020-10-14 12:24
@Eothred yes that's good. Please make a pull request ;-)

**Closed** 2020-10-16 07:46 UTC
