### ISSUE TITLE
Remi is unstable on Linux (was Dialogs are unstable on other other than loopback)

### ISSUE THREAD

**Issue by KenT2** [dddomodossola/remi#169] opened 2017-01-07 13:26 UTC
Trying to use the method for multiple level dialogs as suggested by you in #167 without success so went back to the widgets_overview_app.py

The input and fileselection dialogs work OK when IP is 127.0.0.1 and the App is used from the local machine, but are unstable when IP is 192.168.1.67 and the App is used from another machine using Firefox or Chrome.

Tried an issue of Remi from about May 2016 and it works fine.

**Comment by dddomodossola** [comment] 2017-01-09 17:08
@KenT2 Hello Ken! Can you describe which kind of instability you found using dialogs on remote machines?

**Comment by KenT2** [comment] 2017-01-11 16:57
Using widgets_overview_app.py

The effect is very variable and random
Open Input Dialog - the text in the input field is sometimes not returned
Open File Selection Dialog - the list of files is sometimes not shown; sometimes the list is shown but pressing OK has no effect or sometimes it has an effect but the file path is not returned, or sometimes pressing OK works after 5 seconds.

I understand the remote browser should mirror the local browser, Pressing Open input Dialog on local browser sometimes both browsers show the dialog, sometimes only the local browser.
Server is on Raspbian Jessie, browsers that have not worked are Firefox and Chrome on Lubuntu and Windows 10

Log of doing 
    start(MyApp, debug=True, address='0.0.0.0',start_browser=True)
attached
I opened a remote browser, tried to use input dialog then file selection dialog

[log.txt](https://github.com/dddomodossola/remi/files/699485/log.txt)


Hop this helps

**Comment by dddomodossola** [comment] 2017-01-12 14:51
@KenT2 Thank you so much for these additional info Ken. I tried to reproduce the problem but without success. The log file itself doesn't show nothing strange.
May I ask you to report other info (if you will encounter again this problem)? When you see something strange with this, try to refresh the page and see if the expected behaviour happens. For example, in widgets_overview_app.py when the info label doesn't show the value returned by an input dialog.

**Comment by KenT2** [comment] 2017-01-14 20:31
@dddomodossola 
Thanks for looking at this. 

Did you try it with a raspberry Pi as server?. I am wondering if it's a timing problem due to a slow server.

I have investigated further. See attached log

Sometimes when I return from  the file selection dialog the label field contains no new selection or the path string is partially truncated. This is sometimes accompanied by various error messages as you will see from the attached log.  If I refresh the browser the correct path is then displayed. 

The correct information is always displayed on the local browser

Is it correct that the local browser should show no websocket connections?

[log2.txt](https://github.com/dddomodossola/remi/files/706197/log2.txt)

**Comment by KenT2** [comment] 2017-03-12 19:57
I think I have identified the cause of the instability. When running Remi on a Linux machine it seems necessary to set the websocket timeout in server.py (around line 141):

    def handle(self):
        self.log.debug('handle')
        # on some systems like ROS, the default socket timeout
        # is less than expected, we force it to infinite (None) as default socket value
        #krt added
        self.request.settimeout(None)

'None' seems to be necessary, setting a value of 10000 seconds did not solve the problem. 

The settimeout() statement was in the May 2016 version but omitted from the latest version.


My investigations:
Server using Python 2.7. The browser on remote machine is Firefox or Chrome
The symptoms do not occur with a version of Remi from about May 2016
The symptoms do not occur when using a browser on the same machine as the server.
The symptoms do not occur when running the server on windows 10 .
The symptoms occur when running the server on Linux with the latest version of Remi, both on the Raspberry Pi and on Lubuntu.

Using widgets_overview_app.py Open the File Selection dialog. If the number of items in the directory is small then all is OK. If the number of items is large then the system hangs. It eventually times out and then re-connects.

**Comment by saewoonam** [comment] 2017-03-13 20:50
+1
I just ran into the same problem with the file selection dialog... If the file list is too long, the browser does not update the screen and the screen is  blank.

**Comment by dddomodossola** [comment] 2017-03-13 21:02
@KenT2 @saewoonam Thank you a lot for reporting and investigating, will make a fix for this ;-)

**Comment by mgeorgia** [comment] 2017-03-30 16:31
Quick addition.  I'm running remi on a beaglebone black and I'm using something similar to the plotly example posted here to serve up data collected by the adc.

If my array got too long, I was getting a UTF-8 encoding error from within my browser and my page would need to refresh.  I spent a ton of time ensuring all my data was properly encoded, but it didn't get rid of the problem.  By adding the line KenT2 showed above, self.request.settimeout(None), my problem was fixed.  
Additionally, I used a dummy data set and ran it on windows without the added line, and it worked just fine.  Not sure if it's a linux thing or if it's the fact that the beaglebone black is much slower than my pc is.  Hopefully this info is helpful.

**Comment by saewoonam** [comment] 2017-03-31 01:06
Thanks for posting this workaround for plotly plots with a large amount of data.  I have had this problem on my raspberry pi data acquisition system, and my work around was to force the page to refresh with a javascript snippet triggered by Remi.

This makes my web interface much better.  Thanks you very much.

**Comment by nzjrs** [comment] 2017-03-31 11:55
I don't know why this commit got removed. Maybe a bad merge? I couldnt find
a commit that removed it

**Comment by dddomodossola** [comment] 2017-03-31 12:24
@nzjrs I think you are right John, probably a bad merge. I'm waiting making this change, because I had no time to test it and I firstly would understand the motivation that causes the problem. Ok that instruction solves it, but why? What happen?

**Comment by nzjrs** [comment] 2017-03-31 12:29
the same reason as it was originally added. other bad software or libraries
set a *global* shorter socket timeout and we lose the websocket connection
because it times out with lots of data or bad network. Why it doesn't
reconnect reliably, I don't know

**Comment by dddomodossola** [comment] 2017-03-31 12:33
Ok, now I remember, it was hard to detect. I will try to make the change soon. ;-)

**Comment by KenT2** [comment] 2017-04-01 09:14
remi does reconnect reliably every time, however by that time the damage is done because a message has been lost or truncated. Refreshing the browser does sometimes display the correct information but if the failure is due to show() or hide() then state is lost especially with nested dialogs.

I did try a large timeout value (10000 seconds) but it still failed. Only None worked. I suspect the problem is more deep seated than a global variable.

**Closed** 2017-04-03 15:59 UTC
