### ISSUE TITLE
Problem using event listener functions

### ISSUE THREAD

**Issue by HilaGast** [dddomodossola/remi#225] opened 2018-06-25 16:52 UTC
I'm trying to do my first steps using remi. I walked through both the 'brief tutorial' and some examples and I keep getting attribute error every time I try to use the '.connect' function:
**AttributeError: 'function' object has no attribute 'connect'**

Any idea what the problem might be?

Thank you :)

**Comment by dddomodossola** [comment] 2018-06-25 17:47
@HilaGast you are probably looking at the readme on the master branch and installed the stable release from pypi. Install the moat recent version on master branch. ;-)

Or instead you can look for an old readme version from here https://github.com/dddomodossola/remi/releases

**Comment by sbooeshaghi** [comment] 2018-06-26 02:31
I was also getting the same errors, it seems like if I do `pip install remi==1.1` and also `git checkout tags/v1.1` then the examples will run. However if I am on the master branch then the examples will not run.

There seems to be some sort of issue with the event listener functions where some parts of the codebase using `widget.onclick.connect()` and others are using `widget.set_on_click_listener()`.

Its also possible the remi package hasn't been updated on pypi? Unsure! 

As a note, when I try to run the examples on the master branch I get the following error

~~~~Traceback (most recent call last):
  File ".../anaconda/envs/pmp_cntrl/lib/python2.7/site-packages/remi/server.py", line 809, in do_GET
    self.client.root = self.main(*self.server.userdata)

  File "helloworld_app.py", line 38, in main
    bt.onclick.connect(self.on_button_pressed)

AttributeError: 'function' object has no attribute 'connect'

**Comment by dddomodossola** [comment] 2018-06-26 05:30
Actually on master branch there is a most advanced experimental version. You installed remi from pypi where lives the stable version. 
Install the experimental version with this command:

    pip install git+https://github.com/dddomodossola/remi.git

And it will work fine ;-)

**Comment by dddomodossola** [comment] 2018-06-26 14:29
Please give me some more info:
- Which browser are you using?
- On which OS?
- python version?

This seems to be a bug.

**Comment by sbooeshaghi** [comment] 2018-06-26 16:09
Hope this helps!
~~~~

Google Chrome | 66.0.3359.181 (Official Build) (64-bit)
-- | --
Revision | a10b9cedb40738cb152f8148ddab4891df876959-refs/branch-heads/3359@{#828}
OS | Mac OS X
JavaScript | V8 6.6.346.32
Flash | 30.0.0.113 /Users/sinabooeshaghi/Library/Application Support/Google/Chrome/PepperFlash/30.0.0.113/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome -psn_0_49164 --flag-switches-begin --flag-switches-end
Executable Path | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
Profile Path | /Users/sinabooeshaghi/Library/Application Support/Google/Chrome/Profile 2
Variations | c134752e-b8b72c885f419cc9-ca7d8d803542328a-cbc25d7a31101bd6-71a713bfa6674cf-ca7d8d803095aa95-3f4a17dfd52c4ff7-d52c4ff747e5d3db-3d47f4f44dc30737-b8a5ea0814ae850d-3f4a17dfa605b19e-33c3eba5589b4e9f-3f4a17dff9884634-659882c0121ae2bc-ca7d8d8057f575bb-3d47f4f4ceff87ec-3f4a17df44827ee5-ca7d8d809b54a08f-28ad44a9eab0f00-3f4a17df120703dd-3f4a17dfd0ecf1da-ca7d8d8086ba59b4-477edaaef05a96e-e2c3ac679773d3bd-f23d1dea8e3b2dc5-93702590165e16d1-3f4a17df9e5c75f1-1039a221c322f799-2dbe5f93de1fbf2-3d47f4f4f79cb77b-3d47f4f44ea303a6-ecbb250e3d7e3f6a-2eb014552b33233e-cc2bd7de25fc488a-4d2fac8772606c4f-3f4a17df58a025e3-c2b417022a32876a-ca7d8d80ff29b1bd-8ec307734bc337ce-535cb40a9a2f4e5b-d226bfeb494d8760-52325d43f47ae82a-86f22ee53ac60855-486e2a9cf296190c-4a95e4f14442aae2-75cb33fced1d377-e1cc0f1412e17bc5-e1cc0f1475f0f0a0-e1cc0f14e2b18481-5c63917ae7e71889-4ad60575b1ceb06f-d137233494e68624-803f8fc4

$ system_profiler SPSoftwareDataType

    System Software Overview:

      System Version: macOS 10.12.6 (16G1036)
      Kernel Version: Darwin 16.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Sina’s MacBook Pro
      User Name: Sina Booeshaghi (sinabooeshaghi)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 33 days 18:29

$python -V
Python 2.7.15 :: Anaconda, Inc.

$ conda info
     active environment : pmp_cntrl
    active env location : .../anaconda/envs/pmp_cntrl
            shell level : 1
       user config file : .../.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : not installed
         python version : 2.7.13.final.0
       base environment : .../anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : .../anaconda/pkgs
                          .../.conda/pkgs
       envs directories : .../anaconda/envs
                          .../.conda/envs
               platform : osx-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/2.7.13 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

**Comment by dddomodossola** [comment] 2018-06-27 05:32
@sbooeshaghi thank you so much for these  information. I will try to reproduce the problem and provide a fix. It seems that your browser is returning encrypted cookies, an unexpected condition in remi. Do you have the possibility to test it with another browser? (Use the parameter **start_browser = False** to avoid opening the browser automatically)

**Comment by dddomodossola** [comment] 2018-06-28 07:36
I'm unable to reproduce the problem. I tried same Python and browser versions on a Windows machine, unfortunately I haven't a MacOS.

**Comment by dddomodossola** [comment] 2018-07-30 08:16
Should be fixed by the last updates. Without additional information, and unable to reproduce the problem, I close this issue.

**Closed by dddomodossola** 2018-07-30 08:16 UTC
